import type { ComponentType, ReactNode } from "react";

/**---
 * ## ![logo](https://github.com/voodoofugu/demo-workbench/raw/main/src/assets/demo-workbench-logo.png)
 * ### ***DemoComponentProps***:
 * props the workbench passes to a demo's default component.
 * @description
 * A demo is a normal React component. The workbench renders it both as a small
 * grid preview and as the opened full-screen view, and passes:
 * - `pageName` — the demo's stable name (its `DemoItem.name`).
 * - `isActive` — `true` only while the demo is opened full-screen, `false` in the
 *   grid preview. Gate expensive work (timers, canvases, data fetching) on it so
 *   it runs only for the opened demo, not for every card in the pool.
 * - `children` — the host overlay produced by `renderDemoContent`, provided only
 *   when opened. Render it wherever the demo wants the project layer.
 * @example
 * ```tsx
 * export default function ProfileCardDemo({ isActive, children }: DemoComponentProps) {
 *   return (
 *     <div className="screen">
 *       {isActive ? <HeavyAnimation /> : <StaticPreview />}
 *       {children}
 *     </div>
 *   );
 * }
 * ```
 */
export type DemoComponentProps = {
  /**
   * The demo's stable name.
   * @description
   * Matches the `DemoItem.name` from the generated manifest and can be used by a demo for analytics, labels or conditional rendering.
   */
  pageName?: string;
  /**
   * Whether this render is the opened demo.
   * @description
   * `true` only in the full-screen opened view; `false` in grid previews. Use it to pause expensive work while a demo is only visible as a preview card.
   * @default false
   */
  isActive?: boolean;
  /**
   * Host overlay content.
   * @description
   * Value returned by `DemoWorkbenchProps.renderDemoContent`, provided only for the opened demo. Grid previews do not receive this content.
   */
  children?: ReactNode;
};

/**---
 * ## ![logo](https://github.com/voodoofugu/demo-workbench/raw/main/src/assets/demo-workbench-logo.png)
 * ### ***DemoModule***:
 * module shape returned by a demo loader.
 * @description
 * A demo module must expose a default React component. It declares its own scoped CSS by exporting `cssFiles` — compiled file names (without extension) that the workbench loads through `styled-atom` before the preview is rendered. Co-locating the list with the demo keeps a single, obvious place for a demo's styles.
 * @example
 * ```ts
 * // ButtonDemo.tsx
 * export const cssFiles = ["button-demo"];
 * export default function ButtonDemo() { ... }
 * ```
 */
export type DemoModule = {
  /**
   * Demo React component.
   * @description
   * Rendered both inside the grid preview cell and inside the opened-demo modal. It receives `DemoComponentProps`.
   */
  default: ComponentType<DemoComponentProps>;
  /**
   * CSS files required by this demo.
   * @description
   * File names loaded through `DemoWorkbenchProps.styleLoader` before rendering the preview. Declare them in the demo module as `export const cssFiles = ["button-demo"]`.
   */
  cssFiles?: string[];
};

/**---
 * ## ![logo](https://github.com/voodoofugu/demo-workbench/raw/main/src/assets/demo-workbench-logo.png)
 * ### ***DemoItem***:
 * one searchable item in the workbench grid.
 * @description
 * `name` is used for labels, search, hash state, storage keys and the `pageName` prop passed to the loaded component. Keep it stable between sessions.
 * @example
 * ```ts
 * const demos: DemoItem[] = [
 *   { name: "Button", load: () => import("./demos/ButtonDemo") },
 * ];
 * ```
 */
export type DemoItem = {
  /**
   * Stable demo name.
   * @description
   * Used for search, labels, hash navigation, storage state and the `pageName` prop. Keep it stable after users begin bookmarking or sharing links.
   */
  name: string;
  /**
   * Optional display title.
   * @description
   * Reserved for host-specific labels when the stable `name` should remain machine-friendly. If omitted, the workbench displays `name`.
   */
  title?: string;
  /**
   * Lazy demo module loader.
   * @description
   * Usually generated by `runWorkbenchCompile` as `() => import("./MyDemo")`. The module must expose a default React component and can export `cssFiles`.
   */
  load: () => Promise<DemoModule>;
};

/**---
 * ## ![logo](https://github.com/voodoofugu/demo-workbench/raw/main/src/assets/demo-workbench-logo.png)
 * ### ***DemoWorkbenchStyleLoader***:
 * CSS loader used by the workbench style store.
 * @description
 * Pass a URL prefix string for the common static-file case, for example `"/workbench-css/"`. The workbench will fetch `${name}.css` from that prefix. Pass a function when the host project needs custom loading or a bundler configured to import CSS as text.
 * @example
 * ```tsx
 * <DemoWorkbench styleLoader="/workbench-css/" demos={demos} />
 * ```
 */
export type DemoWorkbenchStyleLoader =
  | string
  | ((name: string) => unknown | Promise<unknown>);

/**---
 * ## ![logo](https://github.com/voodoofugu/demo-workbench/raw/main/src/assets/demo-workbench-logo.png)
 * ### ***DemoWorkbenchAutoScaleDimension***:
 * one enabled or disabled auto-scale axis.
 * @description
 * Use a number as the reference size in CSS pixels, or `null` to opt that axis out of workbench scaling.
 */
export type DemoWorkbenchAutoScaleDimension = number | null;

/**---
 * ## ![logo](https://github.com/voodoofugu/demo-workbench/raw/main/src/assets/demo-workbench-logo.png)
 * ### ***DemoWorkbenchAutoScaleOptions***:
 * opened-demo reference size for automatic down-scaling.
 * @description
 * Each axis is optional. Enabled axes scale the opened demo down when the available workbench area is smaller than the reference size.
 * @example
 * ```ts
 * const autoScale: DemoWorkbenchAutoScaleOptions = {
 *   width: 1200,
 *   height: null,
 * };
 * ```
 */
export type DemoWorkbenchAutoScaleOptions = {
  /**
   * Reference workspace width in CSS pixels.
   * @description
   * The opened demo scales down when its available width is smaller than this value. Pass `null` to leave horizontal scaling to the demo itself.
   */
  width?: DemoWorkbenchAutoScaleDimension;
  /**
   * Reference workspace height in CSS pixels.
   * @description
   * The opened demo scales down when its available height is smaller than this value. Pass `null` to leave vertical scaling to the demo itself.
   */
  height?: DemoWorkbenchAutoScaleDimension;
};

/**---
 * ## ![logo](https://github.com/voodoofugu/demo-workbench/raw/main/src/assets/demo-workbench-logo.png)
 * ### ***DemoWorkbenchAutoScale***:
 * reference workspace size used by opened-demo auto scaling.
 * @description
 * The opened demo is scaled down only for enabled axes when the available workbench area becomes smaller than this reference size. Omit the prop to keep auto scaling disabled, or pass `null` for one axis to let the demo handle that axis by itself.
 * @example
 * ```ts
 * const autoScale: DemoWorkbenchAutoScale = { width: 1200, height: null };
 * ```
 */
export type DemoWorkbenchAutoScale = DemoWorkbenchAutoScaleOptions | false;

/**---
 * ## ![logo](https://github.com/voodoofugu/demo-workbench/raw/main/src/assets/demo-workbench-logo.png)
 * ### ***DemoWorkbenchProps***:
 * props for the reusable React workbench shell.
 * @description
 * Minimal setup is a title, generated `demos` and optional style loading. The host project keeps ownership of demo components, CSS imports, project overlays and optional opened-demo content.
 * @example
 * ```tsx
 * <DemoWorkbench
 *   title="Project demos"
 *   demos={demos}
 *   styleLoader="/workbench-css/"
 *   baseStyles={["output", "theme"]}
 * />
 * ```
 */
export type DemoWorkbenchProps = {
  /**
   * Workbench title.
   * @description
   * Shown in the header and used as the browser document title while the workbench is mounted.
   * @default "Demo Workbench"
   */
  title?: string;
  /**
   * Demo manifest.
   * @description
   * Array generated by `runWorkbenchCompile({ demos })` or written manually by the host project. Each item lazy-loads one demo module.
   */
  demos: DemoItem[];
  /**
   * Dynamic CSS loader.
   * @description
   * Use a URL prefix string for static CSS files, for example `"/workbench-css/"`. The workbench fetches `${name}.css` from that prefix. Pass a function only when the host needs custom loading or a bundler configured to import CSS as text.
   */
  styleLoader?: DemoWorkbenchStyleLoader;
  /**
   * Base CSS files for the host project.
   * @description
   * File names loaded through `styleLoader` before demo-specific CSS. Use this for shared reset/theme/output styles needed by most demos.
   */
  baseStyles?: string[];
  /**
   * Opened-demo auto scaling.
   * @description
   * Reference size used to scale the opened demo down when the browser area is smaller. Omit or pass `false` to disable workbench auto scaling.
   */
  autoScale?: DemoWorkbenchAutoScale;
  /**
   * Opened-demo host overlay renderer.
   * @description
   * Called only for the opened demo. Its result is passed to the demo component as `children`, allowing the host app to render project-owned overlays, portals or debugging UI.
   */
  renderDemoContent?: (pageName: string) => ReactNode;
  /**
   * Opened-demo body background.
   * @description
   * Inline CSS background value applied behind the opened demo body.
   * @default "#fff"
   */
  bodyBg?: string;
};
